### ISSUE TITLE
Add a README file to the repository

### ISSUE THREAD

**Issue by soniasingla** [shardeum/network-status#4]
## Description

Add readme file to the repo, it should have:
- An overview of the project
- Instructions for setting up the project locally
- Instructions for running the project
- Any other relevant information

For reference, watch the  Build in Public Livestream videos: https://youtu.be/WQ0QB8jywK8?si=KzNOoVbU5BszuMK0

**Comment by kaksv** [comment]
Can I take this on?

**Comment by kenny-io** [comment]
Hi @kaksv yes you can, I will assign this issue to you now and if you have any questions, keep the conversation going on this issue or start a new discussion here https://github.com/shardeum/shardeum/discussions/new/choose

**Comment by kaksv** [comment]
Hey @kenny-io , I have cloned the repo and running i am running it but the backende returns an error of 'ERR_INVALID_URL'.
I think the url was stored in the .env file which was not uploaded as part of the repo. Any assistance on that?

**Comment by kaksv** [comment]
Alright
